name: Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2

      - name: Install xcaddy
        run: |
          go install github.com/caddyserver/xcaddy/cmd/xcaddy@latest
          echo 'export PATH=$PATH:$HOME/go/bin' >> $HOME/.bashrc
          source $HOME/.bashrc
          xcaddy --version

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker buildx create --name caddy
          docker buildx use caddy
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            -t ${{ secrets.DOCKER_USERNAME }}/caddy-with-plugins:${{ github.sha }} \
            --build-arg CADDY_VERSION=latest \
            .
          docker buildx rm caddy
          docker push ${{ secrets.DOCKER_USERNAME }}/caddy-with-plugins:${{ github.sha }}
